# Generated by Django 5.1.6 on 2025-02-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('equipment', models.CharField(max_length=255)),
                ('primary_muscle', models.CharField(max_length=255)),
                ('secondary_muscle', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='exercises/')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='focus_areas',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='main_goal',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='user', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='training_frequency',
            field=models.IntegerField(default=3),
        ),
    ]
